apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
      - name: random-string
        image: cronosm4m/cryptomator:latest
        ports:
        - containerPort: 3000